const eLOADErrorCodes = {
"100": 'Transaction is pending (only when you call enquiry method before top up process doesn’t complete).',
'101': 'Invalid merchant',
'102': 'Your account is temporary closed',
'103': 'Invalid IP address',
'107': 'Phone Number is required',
'108': 'Order Number is required',
'109': 'Request requires parameter',
'200': 'Success',
'301': 'Failed top up to your phone number',
'302': "Sim card didn't activated",
'303': 'Operator signal is low.',
'305': "We can't top up because of E-load sim",
'400': 'Token is required.',
'401': 'The Token has expired',
'406': 'Top up Amount is invalid.',
'407': 'Phone Number is invalid.',
'408': 'Invalid OrderNumber. Maximun characters is 50.',
'409': 'OrderNumber is already existed.',
'410': 'Invalid merchant balance.',
'412': 'Your balance is lower than request amount',
'413': 'Operator is temporary closed',
'414': 'Order number does not exist (only when you call the enquiry API method)',
'415': 'Phone number is wrong or invalid.',
'416': "Can’t topup same phone number with same amount within two minutes(only Telenor)",
'417': "Can’t topup same phone number with same amount within five minutes(only Ooredoo)",
'501': 'Unknown Error',
'502': 'Invalid PackageCode',
'503': "Doesn’t match package’s operator and request phone’s operator",
'506': 'Package is expired.',
'507': 'Package is temporary closed.',
}

export default eLOADErrorCodes;