const IMFeedActionsConstants = {
  SET_MAIN_FEED_POSTS: 'SET_MAIN_FEED_POSTS',
  SET_NEWFEEDs: 'SET_NEWFEEDs',
  SET_MAIN_FEED_POST_REACTIONS: 'SET_MAIN_FEED_POST_REACTIONS',
  SET_DISCOVER_FEED_POSTS: 'SET_DISCOVER_FEED_POSTS',
  SET_CURRENT_USER_FEED_POSTS: 'SET_CURRENT_USER_FEED_POSTS',
  SET_MAIN_STORIES: 'SET_MAIN_STORIES',
  DID_SUBSCRIBE: 'DID_SUBSCRIBE_TO_MAIN_FEED',
  SET_FIRST_POST: 'SET_FIRST_POST',
  SET_STATUS: 'SET_STATUS',
  INSERT_MAIN_FEED_POSTS: 'INSERT_MAIN_FEED_POSTS',
  INSERT_NEWFEEDS: 'INSERT_NEWFEEDS',
  INSERT_MORE_MAIN_FEED_POSTS: 'INSERT_MORE_MAIN_FEED_POSTS',
  INSERT_MORE_NEWFEEDS: 'INSERT_MORE_NEWFEEDS',
  EDIT_NEWFEEDS: 'EDIT_NEWFEEDS',
  REMOVE_POST: 'REMOVE_POST',
  SET_PROFILE_FEEDS: 'SET_PROFILE_FEEDS',
  SET_OTHER_PROFILE_FEEDS: 'SET_OTHER_PROFILE_FEEDS',
  EDIT_PROFILE_FEEDS: 'EDIT_PROFILE_FEEDS',
  REMOVE_PROFILE_POST: 'REMOVE_PROFILE_POST',
  INSERT_PROFILE_FEEDS: 'INSERT_PROFILE_FEEDS',
  EDIT_POST_REACTIONS: 'EDIT_POST_REACTIONS',
  EDIT_PROFILE_POST_REACTIONS: 'EDIT_PROFILE_POST_REACTIONS',
  SET_EDITED_PROFILE_STATUS: 'SET_EDITED_PROFILE_STATUS',
  SET_PROFILE_EDITED_POST: 'SET_PROFILE_EDITED_POST',
  EDIT_OTHER_PROFILE_POST_REACTIONS: 'EDIT_OTHER_PROFILE_POST_REACTIONS'
};

export default IMFeedActionsConstants;
