const IMNotificationActionsConstants = {
  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
  DID_SUBSCRIBE: 'DID_SUBSCRIBE_TO_NOTIFICATIONS',
  SET_NOTICOUNT: 'SET_NOTICOUNT',
  SET_CHAT_NOTICOUNT: 'SET_CHAT_NOTICOUNT',
  SET_CHAT_NOTIFICATIONS: 'SET_CHAT_NOTIFICATIONS',
  SET_FRIEND_NOTIFICATIONS: 'SET_FRIEND_NOTIFICATIONS',
  SET_FRIEND_NOTICOUNT: 'SET_FRIEND_NOTICOUNT'
};

export default IMNotificationActionsConstants;
